package com.example.project.common.exception;

public enum ErrorCode {

    // COMMON
    BAD_REQUEST,

    // GLOBAL
    GLOBAL_ERROR,
    VALIDATION_ERROR,
    INVALID_JSON_FORMAT,
    METHOD_NOT_ALLOWED,
    UNAUTHORIZED,
    NOT_FOUND,
    CONSTRAINT_VIOLATION,

    // AUTH
    AUTH_INVALID_CREDENTIAL,
    AUTH_USER_NOT_FOUND,
    AUTH_USERNAME_EXISTED,
    AUTH_PHONE_EXISTED,
    AUTH_CCCD_EXISTED,
    AUTH_INVALID_PASSWORD,
    AUTH_EMAIL_EXISTED,
    PARAM_TYPE_MISMATCH,

    // AUTH OTP
    AUTH_OTP_NOT_FOUND,
    AUTH_OTP_EXPIRED,
    AUTH_OTP_INVALID,
    AUTH_OTP_COOLDOWN,

    // MAIL
    MAIL_SEND_FAILED,
    NULL_ERROR, MAIL_FORMAT_ERROR,

    ACCOUNT_NOT_APPROVED,
    AUTH_INVALID_CREDENTIALS,

    // FeePayment
    AMOUNT_NULL_ERROR

}
